# NOTE: These configuration flags are stored in this file because they're crate specific.
# When building the wasm binary, they are required. However the wasmpack toolchain builds
# several other tools while running `wasm-pack build`. If these are set as "RUSTFLAGS"
# they will be ingested by the build for the tools, causing those tools to fail to build.
#
# See https://github.com/pluto/web-prover/pull/201#issuecomment-2392115215
#
[build]
[target.wasm32-unknown-unknown]
rustflags=[
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-C",
  "link-args=--shared-memory --max-memory=4294967296",
  "-Z",
  "threads=8",
]
