[target.'cfg(target_arch = "wasm32")']
rustflags=[
  # TODO
  # failed attempts to silence warnings for using unstable compiler options for atomics, issue persists
  # "-Z", "unstable-options",
  # "-A", "unstable_features",
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
]

[alias]
check-wasm="check --target wasm32-unknown-unknown -Z build-std=panic_abort,std --features=websocket"
