[package]
edition="2021"
name   ="web-prover-executor"
version="0.1.0"

[dependencies]
tempfile    ={ workspace=true }
thiserror   ={ workspace=true }
tokio       ={ workspace=true }
tracing     ={ workspace=true }
uuid        ={ workspace=true }
wait-timeout={ workspace=true }
