[book]
authors     =["Pluto"]
description ="Backend for Web Proofs"
language    ="en"
multilingual=false
src         ="."
title       ="Web Prover"

[build]
build-dir                ="."
create-missing           =false # Don't create missing files
extra-watch-dirs         =[]    # Don't watch any extra directories
use-default-preprocessors=false

[preprocessor.links]

[preprocessor.katex]
after=["links"]

[output.linkcheck]
follow-web-links           =true
traverse-parent-directories=true
warning-policy             ="ignore"

# [preprocessor.keeper]
# command     ="mdbook-keeper"
# manifest_dir="."
# externs     =["ronkathon", "rand"]

[output.html]
default-theme       ="dark"
git-repository-url  ="https://github.com/pluto/web-prover"
preferred-dark-theme="ayu"

# [output.html.playground]
# editable=true
# runnable=true

# [rust]
# edition="2021"

# [[output.html.playground.pre-installed-crates]]
# name   ="rand"
# version="0.8"
