name: 'Setup Proofs Environment'
description: 'Sets up build environment'
inputs:
  rust-version:
    description: 'Rust version to install'
    required: false
    default: 'nightly'

runs:
  using: "composite"
  steps:
    - name: Cache Protocol Buffers
      id: cache-protoc
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/protoc
          /usr/local/include/google/protobuf
        key: ${{ runner.os }}-protoc-${{ hashFiles('/usr/local/bin/protoc', '/usr/local/include/google/protobuf/**') }}

    - name: Install Protocol Buffers
      if: steps.cache-protoc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}