name: 'Setup Proofs Environment'
description: 'Sets up build environment'
inputs:
  rust-version:
    description: 'Rust version to install'
    required: false
    default: 'nightly'

runs:
  using: "composite"
  steps:
    - name: Install Protocol Buffers
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}