name: Check

on:
  workflow_call:

jobs:
  clippy:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - web-prover-notary
          - web-prover-client
          - web-prover-core
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: clippy

      - run: cargo clippy -p ${{ matrix.crate }}

  fmt:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: fmt

      - run: rustup component add rustfmt

      - run: cargo fmt --all -- --check

  test:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          crate:
            - web-prover-notary
            - web-prover-client
            - web-prover-core
      steps:
        - uses: actions/checkout@v4

        - uses: ./.github/actions/setup-rust-ubuntu
          with:
            rust-cache-key: test

        - name: Run tests
          run: cargo test -p ${{ matrix.crate }}

  udeps:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - web-prover-notary
          - web-prover-client
          - web-prover-core
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: udeps

      - name: Install cargo-udeps
        run: cargo binstall --no-confirm cargo-udeps

      - name: Check unused dependencies
        run: cargo udeps -p ${{ matrix.crate }}
