name: Check

on:
  workflow_call:

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [web-prover-notary, web-prover-client, web-prover-core]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: clippy-${{ matrix.crate }}

      - name: Run clippy
        continue-on-error: true
        run: cargo clippy -p ${{ matrix.crate }}
        
      # Save the target directory to cache for reuse in test job
      - name: Save target directory
        uses: actions/cache/save@v3
        with:
          path: |
            target/
            ~/.cargo/registry/
            ~/.cargo/git/
          key: build-cache-${{ matrix.crate }}-${{ github.sha }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: fmt

      - run: rustup component add rustfmt

      - run: cargo fmt --all -- --check

  test:
    needs: clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [web-prover-notary, web-prover-client, web-prover-core]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: test-${{ matrix.crate }}
        
      # Restore the target directory from clippy job
      - name: Restore cached build
        uses: actions/cache/restore@v3
        with:
          path: |
            target/
            ~/.cargo/registry/
            ~/.cargo/git/
          key: build-cache-${{ matrix.crate }}-${{ github.sha }}
          restore-keys: |
            build-cache-${{ matrix.crate }}-

      - name: Run tests
        run: cargo test -p ${{ matrix.crate }}

  udeps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [web-prover-notary, web-prover-client, web-prover-core]
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: udeps-${{ matrix.crate }}

      - name: Install cargo-udeps
        run: cargo binstall --no-confirm cargo-udeps

      - name: Check unused dependencies
        continue-on-error: true
        run: cargo udeps -p ${{ matrix.crate }}