on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "hello"

      - uses: Swatinem/rust-cache@v2 # TODO does not work!

      - run: rustup toolchain install nightly-2024-10-28

      - run: sudo apt install -y protobuf-compiler
        if: matrix.os == 'ubuntu-latest'
