name: Test Client Native with TEE

on:
  workflow_call:
    inputs:
      web-prover-circuits-cache-key:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch web-prover-circuits cache
        uses: actions/cache/restore@v4
        with:
          path: proofs/web_proof_circuits
          key: ${{ inputs.web-prover-circuits-cache-key }}

      - name: Download notary
        uses: actions/download-artifact@v4
        with:
          name: "notary.linux.amd64"
          path: "target/release"

      - run: chmod +x target/release/notary

      - name: Download client
        uses: actions/download-artifact@v4
        with:
          name: "client.linux.amd64"
          path: "target/release"

      - run: chmod +x target/release/client

      - run: |
          cargo test -p web-prover-tests
